from django.contrib.gis.db import models

class FloodPoint(models.Model):
    id_1 = models.IntegerField(primary_key=True)
    kdppum = models.CharField(max_length=50, null=True, blank=True)
    namobj = models.CharField(max_length=100)
    remark = models.CharField(max_length=255, null=True, blank=True)
    kdppbs = models.CharField(max_length=50, null=True, blank=True)
    fcode = models.CharField(max_length=50, null=True, blank=True)
    luaswh = models.FloatField(null=True, blank=True)
    uuppp = models.CharField(max_length=50, null=True, blank=True)
    srs_id = models.IntegerField(null=True, blank=True)
    metadata = models.TextField(null=True, blank=True)
    kdepum = models.CharField(max_length=50, null=True, blank=True)
    kdbbps = models.CharField(max_length=50, null=True, blank=True)
    kdcbum = models.CharField(max_length=50, null=True, blank=True)
    wadmkd = models.CharField(max_length=50, null=True, blank=True)
    wadmkc = models.CharField("Kecamatan", max_length=100, null=True, blank=True)
    wadmkk = models.CharField("Kab/Kota", max_length=100, null=True, blank=True)
    wadmpr = models.CharField("Propinsi", max_length=100, null=True, blank=True)
    tipadm = models.IntegerField(null=True, blank=True)
    shape_leng = models.FloatField("Shape Length 1", null=True, blank=True)
    shape_area_1 = models.FloatField("Shape Area 1", null=True, blank=True)
    id_2 = models.IntegerField(null=True, blank=True)
    fid = models.IntegerField(null=True, blank=True)
    shape_length = models.FloatField("Shape Length 2", null=True, blank=True)
    shape_area_2 = models.FloatField("Shape Area 2", null=True, blank=True)
    gridcode = models.IntegerField(null=True, blank=True)
    month = models.CharField(max_length=20, null=True, blank=True)
    year = models.IntegerField(null=True, blank=True)
    dem_min = models.FloatField(null=True, blank=True)
    dem_max = models.FloatField(null=True, blank=True)
    dem_mean = models.FloatField(null=True, blank=True)
    dem_std = models.FloatField(null=True, blank=True)
    avg_slope = models.FloatField(null=True, blank=True)
    potensi_banjir = models.BooleanField(default=False)
    dist_to_river = models.FloatField(null=True, blank=True)
    flood_elev = models.FloatField(null=True, blank=True)
    river_elev = models.FloatField(null=True, blank=True)
    risk_score = models.IntegerField(null=True, blank=True)
    risk_level = models.CharField(max_length=50, null=True, blank=True)

    geometry = models.PointField(srid=4326)
