# Generated by Django 5.0.3 on 2025-02-23 22:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kdppum', models.CharField(blank=True, max_length=50, null=True)),
                ('namobj', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('kdpbps', models.CharField(blank=True, max_length=50, null=True)),
                ('fcode', models.CharField(blank=True, max_length=50, null=True)),
                ('luaswh', models.FloatField(blank=True, null=True)),
                ('uupp', models.CharField(blank=True, max_length=50, null=True)),
                ('srs_id', models.CharField(blank=True, max_length=50, null=True)),
                ('lcode', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.TextField(blank=True, null=True)),
                ('kdebps', models.CharField(blank=True, max_length=50, null=True)),
                ('kdepum', models.CharField(blank=True, max_length=50, null=True)),
                ('kdcbps', models.CharField(blank=True, max_length=50, null=True)),
                ('kdcpum', models.CharField(blank=True, max_length=50, null=True)),
                ('kdbbps', models.CharField(blank=True, max_length=50, null=True)),
                ('kdbpum', models.CharField(blank=True, max_length=50, null=True)),
                ('wadmkd', models.CharField(blank=True, max_length=100, null=True)),
                ('wiadkd', models.CharField(blank=True, max_length=100, null=True)),
                ('wadmkc', models.CharField(blank=True, max_length=100, null=True)),
                ('wiadkc', models.CharField(blank=True, max_length=100, null=True)),
                ('wadmkk', models.CharField(blank=True, max_length=100, null=True)),
                ('wiadkk', models.CharField(blank=True, max_length=100, null=True)),
                ('wadmpr', models.CharField(blank=True, max_length=100, null=True)),
                ('wiadpr', models.CharField(blank=True, max_length=100, null=True)),
                ('tipadm', models.IntegerField(blank=True, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Rainfall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.IntegerField(blank=True, null=True)),
                ('feature_id', models.IntegerField(blank=True, null=True)),
                ('shape_length', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('gridcode', models.IntegerField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
