# Generated by Django 5.0.3 on 2025-03-24 21:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalElevationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('raster', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
            ],
        ),
        migrations.RenameField(
            model_name='administrationregion',
            old_name='kdbpum',
            new_name='kdcbum',
        ),
        migrations.RemoveField(
            model_name='administrationregion',
            name='geometry',
        ),
        migrations.RemoveField(
            model_name='administrationregion',
            name='kdcbps',
        ),
        migrations.RemoveField(
            model_name='administrationregion',
            name='kdcpum',
        ),
        migrations.RemoveField(
            model_name='administrationregion',
            name='kdebps',
        ),
        migrations.RemoveField(
            model_name='administrationregion',
            name='lcode',
        ),
        migrations.RemoveField(
            model_name='administrationregion',
            name='wiadkc',
        ),
        migrations.RemoveField(
            model_name='administrationregion',
            name='wiadkd',
        ),
        migrations.RemoveField(
            model_name='administrationregion',
            name='wiadkk',
        ),
        migrations.RemoveField(
            model_name='administrationregion',
            name='wiadpr',
        ),
        migrations.RemoveField(
            model_name='rainfall',
            name='feature_id',
        ),
        migrations.AddField(
            model_name='administrationregion',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='administrationregion',
            name='luaswh',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='administrationregion',
            name='metadata',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='administrationregion',
            name='namobj',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='administrationregion',
            name='tipadm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
