# Generated by Django 5.0.3 on 2025-05-15 03:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kosan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=255, null=True)),
                ('alamat_lengkap', models.CharField(blank=True, max_length=255, null=True)),
                ('luas_bangunan', models.FloatField(blank=True, null=True)),
                ('link_lengkap_properti', models.URLField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
