# Generated by Django 5.0.3 on 2025-03-24 21:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data_services', '0002_digitalelevationmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='River',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namobj', models.CharField(blank=True, max_length=255, null=True)),
                ('tipsng', models.IntegerField(blank=True, null=True)),
                ('klssng', models.IntegerField(blank=True, null=True)),
                ('fcode', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('srs_id', models.CharField(blank=True, max_length=255, null=True)),
                ('lcode', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.CharField(blank=True, max_length=255, null=True)),
                ('namws', models.CharField(blank=True, max_length=255, null=True)),
                ('namda', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('wmax', models.IntegerField(blank=True, null=True)),
                ('dbtmax', models.IntegerField(blank=True, null=True)),
                ('slprt', models.IntegerField(blank=True, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Slope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('raster', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
            ],
        ),
    ]
