# Generated by Django 5.0.3 on 2025-12-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data_services', '0003_floodarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floodarea',
            name='desa',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='floodarea',
            name='kecamatan',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
