# Generated by Django 5.0.3 on 2026-01-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data_services', '0004_alter_floodarea_desa_alter_floodarea_kecamatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='floodarea',
            name='certainty',
            field=models.FloatField(null=True, verbose_name='Certainty'),
        ),
        migrations.AddField(
            model_name='floodarea',
            name='composite',
            field=models.FloatField(db_column='composite_', null=True, verbose_name='Composite'),
        ),
        migrations.AddField(
            model_name='floodarea',
            name='confidence',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='floodarea',
            name='dominant_f',
            field=models.CharField(max_length=80, null=True, verbose_name='Dominant Factor'),
        ),
        migrations.AlterField(
            model_name='floodarea',
            name='high_risk',
            field=models.FloatField(db_column='high_risk_', null=True, verbose_name='High Risk Area'),
        ),
        migrations.AlterField(
            model_name='floodarea',
            name='reason',
            field=models.CharField(max_length=231),
        ),
    ]
