# Generated by Django 5.0.3 on 2025-03-24 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data_services', '0005_alter_administrationregion_geom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digitalelevationmodel',
            old_name='raster',
            new_name='rast',
        ),
    ]
