# Generated by Django 5.0.3 on 2026-01-14 09:21

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data_services', '0005_floodarea_certainty_floodarea_composite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floodarea',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
