# Generated by Django 5.0.3 on 2026-02-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data_services', '0006_alter_floodarea_geom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floodarea',
            options={'ordering': ['-risk_score'], 'verbose_name': 'Flood Area', 'verbose_name_plural': 'Flood Areas'},
        ),
        migrations.RemoveField(
            model_name='floodarea',
            name='bulan',
        ),
        migrations.RemoveField(
            model_name='floodarea',
            name='c_elevatio',
        ),
        migrations.RemoveField(
            model_name='floodarea',
            name='certainty',
        ),
        migrations.RemoveField(
            model_name='floodarea',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='floodarea',
            name='desa',
        ),
        migrations.RemoveField(
            model_name='floodarea',
            name='dominant_f',
        ),
        migrations.RemoveField(
            model_name='floodarea',
            name='extreme_ar',
        ),
        migrations.RemoveField(
            model_name='floodarea',
            name='high_risk',
        ),
        migrations.RemoveField(
            model_name='floodarea',
            name='kecamatan',
        ),
        migrations.RemoveField(
            model_name='floodarea',
            name='pct_low',
        ),
        migrations.RemoveField(
            model_name='floodarea',
            name='pct_medium',
        ),
        migrations.RemoveField(
            model_name='floodarea',
            name='pct_very_l',
        ),
        migrations.RemoveField(
            model_name='floodarea',
            name='risk_class',
        ),
        migrations.RemoveField(
            model_name='floodarea',
            name='tahun',
        ),
        migrations.AddField(
            model_name='floodarea',
            name='FCODE',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='floodarea',
            name='KDBBPS',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='floodarea',
            name='KDBPUM',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='floodarea',
            name='KDCBPS',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='floodarea',
            name='KDCPUM',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='floodarea',
            name='KDEBPS',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='floodarea',
            name='KDEPUM',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='floodarea',
            name='KDPBPS',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='floodarea',
            name='KDPPUM',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='floodarea',
            name='LCODE',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='floodarea',
            name='LUASWH',
            field=models.FloatField(blank=True, null=True, verbose_name='Luas Wilayah'),
        ),
        migrations.AddField(
            model_name='floodarea',
            name='METADATA',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodarea',
            name='NAMOBJ',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Nama Objek'),
        ),
        migrations.AddField(
            model_name='floodarea',
            name='REMARK',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='floodarea',
            name='SHAPE_Area',
            field=models.FloatField(blank=True, null=True, verbose_name='Shape Area'),
        ),
        migrations.AddField(
            model_name='floodarea',
            name='SHAPE_Leng',
            field=models.FloatField(blank=True, null=True, verbose_name='Shape Length'),
        ),
        migrations.AddField(
            model_name='floodarea',
            name='SRS_ID',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='floodarea',
            name='TIPADM',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Tipe Administrasi'),
        ),
        migrations.AddField(
            model_name='floodarea',
            name='UUPP',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='floodarea',
            name='WADMKC',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Wilayah Adm Kecamatan'),
        ),
        migrations.AddField(
            model_name='floodarea',
            name='WADMKD',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Wilayah Adm Kelurahan/Desa'),
        ),
        migrations.AddField(
            model_name='floodarea',
            name='WADMKK',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Wilayah Adm Kabupaten/Kota'),
        ),
        migrations.AddField(
            model_name='floodarea',
            name='WADMPR',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Wilayah Adm Provinsi'),
        ),
        migrations.AddField(
            model_name='floodarea',
            name='WIADKC',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='floodarea',
            name='WIADKD',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='floodarea',
            name='WIADKK',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='floodarea',
            name='WIADPR',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='floodarea',
            name='c_elev',
            field=models.FloatField(blank=True, null=True, verbose_name='Contribution: Elevation'),
        ),
        migrations.AddField(
            model_name='floodarea',
            name='cert',
            field=models.FloatField(blank=True, null=True, verbose_name='Certainty'),
        ),
        migrations.AddField(
            model_name='floodarea',
            name='conf',
            field=models.FloatField(blank=True, null=True, verbose_name='Confidence'),
        ),
        migrations.AddField(
            model_name='floodarea',
            name='dominant',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Dominant Factor'),
        ),
        migrations.AddField(
            model_name='floodarea',
            name='pixel_coun',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Pixel Count'),
        ),
        migrations.AlterField(
            model_name='floodarea',
            name='area_ha',
            field=models.FloatField(blank=True, null=True, verbose_name='Area (Hectares)'),
        ),
        migrations.AlterField(
            model_name='floodarea',
            name='c_landuse',
            field=models.FloatField(blank=True, null=True, verbose_name='Contribution: Land Use'),
        ),
        migrations.AlterField(
            model_name='floodarea',
            name='c_prox',
            field=models.FloatField(blank=True, null=True, verbose_name='Contribution: Proximity'),
        ),
        migrations.AlterField(
            model_name='floodarea',
            name='c_rainfall',
            field=models.FloatField(blank=True, null=True, verbose_name='Contribution: Rainfall'),
        ),
        migrations.AlterField(
            model_name='floodarea',
            name='c_slope',
            field=models.FloatField(blank=True, null=True, verbose_name='Contribution: Slope'),
        ),
        migrations.AlterField(
            model_name='floodarea',
            name='c_twi',
            field=models.FloatField(blank=True, null=True, verbose_name='Contribution: TWI'),
        ),
        migrations.AlterField(
            model_name='floodarea',
            name='composite',
            field=models.FloatField(blank=True, db_column='composite_', null=True, verbose_name='Composite Risk'),
        ),
        migrations.AlterField(
            model_name='floodarea',
            name='p_elevatio',
            field=models.FloatField(blank=True, null=True, verbose_name='Physical: Elevation'),
        ),
        migrations.AlterField(
            model_name='floodarea',
            name='p_landuse',
            field=models.FloatField(blank=True, null=True, verbose_name='Physical: Land Use'),
        ),
        migrations.AlterField(
            model_name='floodarea',
            name='p_prox',
            field=models.FloatField(blank=True, null=True, verbose_name='Physical: Proximity'),
        ),
        migrations.AlterField(
            model_name='floodarea',
            name='p_rainfall',
            field=models.FloatField(blank=True, null=True, verbose_name='Physical: Rainfall'),
        ),
        migrations.AlterField(
            model_name='floodarea',
            name='p_slope',
            field=models.FloatField(blank=True, null=True, verbose_name='Physical: Slope'),
        ),
        migrations.AlterField(
            model_name='floodarea',
            name='p_twi',
            field=models.FloatField(blank=True, null=True, verbose_name='Physical: TWI'),
        ),
        migrations.AlterField(
            model_name='floodarea',
            name='pct_extrem',
            field=models.FloatField(blank=True, null=True, verbose_name='Percent Extreme'),
        ),
        migrations.AlterField(
            model_name='floodarea',
            name='pct_high',
            field=models.FloatField(blank=True, null=True, verbose_name='Percent High'),
        ),
        migrations.AlterField(
            model_name='floodarea',
            name='pct_very_h',
            field=models.FloatField(blank=True, null=True, verbose_name='Percent Very High'),
        ),
        migrations.AlterField(
            model_name='floodarea',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Risk Reason'),
        ),
        migrations.AlterField(
            model_name='floodarea',
            name='risk_max',
            field=models.FloatField(blank=True, null=True, verbose_name='Risk Maximum'),
        ),
        migrations.AlterField(
            model_name='floodarea',
            name='risk_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Risk Score'),
        ),
        migrations.AlterField(
            model_name='floodarea',
            name='severity',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Severity Level'),
        ),
        migrations.AddIndex(
            model_name='floodarea',
            index=models.Index(fields=['WADMKD', 'WADMKC'], name='spatial_dat_WADMKD_80b4cb_idx'),
        ),
        migrations.AddIndex(
            model_name='floodarea',
            index=models.Index(fields=['severity'], name='spatial_dat_severit_7d7292_idx'),
        ),
        migrations.AddIndex(
            model_name='floodarea',
            index=models.Index(fields=['risk_score'], name='spatial_dat_risk_sc_4b6e4a_idx'),
        ),
        migrations.AlterModelTable(
            name='floodarea',
            table='spatial_data_services_floodarea',
        ),
    ]
