# Generated by Django 5.0.3 on 2025-03-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data_services', '0006_rename_raster_digitalelevationmodel_rast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalelevationmodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
