# Generated by Django 5.0.3 on 2025-03-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data_services', '0007_alter_digitalelevationmodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digitalelevationmodel',
            old_name='name',
            new_name='attribute',
        ),
        migrations.RemoveField(
            model_name='digitalelevationmodel',
            name='rast',
        ),
        migrations.AddField(
            model_name='digitalelevationmodel',
            name='fid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitalelevationmodel',
            name='layer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='digitalelevationmodel',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
