# Generated by Django 5.0.3 on 2026-02-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data_services', '0007_alter_floodarea_options_remove_floodarea_bulan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floodarea',
            name='month',
            field=models.IntegerField(blank=True, null=True, verbose_name='Month of Flood Event'),
        ),
        migrations.AddField(
            model_name='floodarea',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year of Flood Event'),
        ),
    ]
