# Generated by Django 5.0.3 on 2025-03-30 18:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data_services', '0008_rename_name_digitalelevationmodel_attribute_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digitalelevationmodel',
            old_name='attribute',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='digitalelevationmodel',
            name='fid',
        ),
        migrations.RemoveField(
            model_name='digitalelevationmodel',
            name='layer',
        ),
        migrations.RemoveField(
            model_name='digitalelevationmodel',
            name='value',
        ),
        migrations.AddField(
            model_name='digitalelevationmodel',
            name='raster',
            field=django.contrib.gis.db.models.fields.RasterField(blank=True, null=True, srid=4326),
        ),
    ]
