# Generated by Django 5.0.3 on 2025-03-30 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data_services', '0009_rename_attribute_digitalelevationmodel_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digitalelevationmodel',
            old_name='raster',
            new_name='rast',
        ),
    ]
