# Generated by Django 5.0.3 on 2025-03-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data_services', '0010_rename_raster_digitalelevationmodel_rast'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalelevationmodel',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
