# Generated by Django 5.0.3 on 2025-03-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data_services', '0011_digitalelevationmodel_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='slope',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slope',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
