# Generated by Django 5.0.3 on 2025-03-30 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data_services', '0012_slope_filename_alter_slope_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slope',
            old_name='raster',
            new_name='rast',
        ),
    ]
