# Generated by Django 5.0.3 on 2025-03-30 19:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data_services', '0013_rename_raster_slope_rast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namobj', models.CharField(blank=True, max_length=255, null=True)),
                ('otodan', models.IntegerField(blank=True, null=True)),
                ('fcode', models.IntegerField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('kodlok', models.CharField(blank=True, max_length=50, null=True)),
                ('srs_id', models.CharField(blank=True, max_length=50, null=True)),
                ('lcode', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.CharField(blank=True, max_length=255, null=True)),
                ('voltap', models.IntegerField(blank=True, null=True)),
                ('dta', models.IntegerField(blank=True, null=True)),
                ('sedimn', models.IntegerField(blank=True, null=True)),
                ('vlsdn', models.IntegerField(blank=True, null=True)),
                ('quaar', models.IntegerField(blank=True, null=True)),
                ('crh', models.IntegerField(blank=True, null=True)),
                ('kpts', models.IntegerField(blank=True, null=True)),
                ('namwas', models.CharField(blank=True, max_length=255, null=True)),
                ('namdas', models.CharField(blank=True, max_length=255, null=True)),
                ('lokasi', models.CharField(blank=True, max_length=255, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
