# Generated by Django 5.0.3 on 2025-04-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data_services', '0014_lake'),
    ]

    operations = [
        migrations.AddField(
            model_name='rainfall',
            name='month',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
