# Generated by Django 5.0.3 on 2025-04-17 11:09

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data_services', '0015_rainfall_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloodRiskPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('month', models.CharField(max_length=20)),
                ('dem_mean', models.FloatField()),
                ('dem_min', models.FloatField()),
                ('dem_max', models.FloatField()),
                ('dem_std', models.FloatField()),
                ('flood_elev', models.FloatField()),
                ('river_elev', models.FloatField(null=True)),
                ('avg_slope', models.FloatField()),
                ('dist_to_river', models.FloatField()),
                ('gridcode', models.IntegerField()),
                ('risk_score', models.IntegerField()),
                ('risk_level', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flood_points', to='spatial_data_services.administrationregion')),
            ],
        ),
    ]
