# Generated by Django 5.0.3 on 2025-04-18 08:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data_services', '0016_floodriskpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokasi', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Titik koordinat (longitude, latitude)', srid=4326, verbose_name='Lokasi Properti')),
                ('nama_properti', models.CharField(max_length=255, verbose_name='Nama Properti')),
                ('alamat_lengkap', models.TextField(blank=True, verbose_name='Alamat Lengkap')),
                ('kelurahan', models.CharField(max_length=100, verbose_name='Kelurahan')),
                ('jalan_terdekat', models.TextField(verbose_name='Jalan Terdekat')),
                ('kategori_properti', models.CharField(max_length=50, verbose_name='Kategori Properti')),
                ('status_properti', models.CharField(max_length=50, verbose_name='Status Properti')),
                ('harga_properti', models.IntegerField(verbose_name='Harga Properti (IDR)')),
                ('luas_bangunan', models.FloatField(blank=True, null=True, verbose_name='Luas Bangunan (m²)')),
                ('luas_tanah', models.FloatField(blank=True, null=True, verbose_name='Luas Tanah (m²)')),
                ('kecamatan', models.CharField(max_length=100, verbose_name='Kecamatan')),
                ('link_lengkap_properti', models.URLField(max_length=500, verbose_name='Link Lengkap Properti')),
            ],
            options={
                'verbose_name': 'Properti',
                'verbose_name_plural': 'Properti',
                'indexes': [models.Index(fields=['nama_properti'], name='spatial_dat_nama_pr_dbb4c4_idx')],
            },
        ),
    ]
