# Generated by Django 5.0.3 on 2025-04-18 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data_services', '0017_property'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='spatial_dat_nama_pr_dbb4c4_idx',
        ),
    ]
