# Generated by Django 5.0.3 on 2025-04-18 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data_services', '0018_alter_property_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='lokasi',
            new_name='geometry',
        ),
    ]
