# Generated by Django 5.0.3 on 2025-04-20 08:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data_services', '0019_rename_lokasi_property_geometry'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloodPoint',
            fields=[
                ('id_1', models.IntegerField(primary_key=True, serialize=False)),
                ('kdppum', models.CharField(blank=True, max_length=50, null=True)),
                ('namobj', models.CharField(max_length=100)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('kdppbs', models.CharField(blank=True, max_length=50, null=True)),
                ('fcode', models.CharField(blank=True, max_length=50, null=True)),
                ('luaswh', models.FloatField(blank=True, null=True)),
                ('uuppp', models.CharField(blank=True, max_length=50, null=True)),
                ('srs_id', models.IntegerField(blank=True, null=True)),
                ('metadata', models.TextField(blank=True, null=True)),
                ('kdepum', models.CharField(blank=True, max_length=50, null=True)),
                ('kdbbps', models.CharField(blank=True, max_length=50, null=True)),
                ('kdcbum', models.CharField(blank=True, max_length=50, null=True)),
                ('wadmkd', models.CharField(blank=True, max_length=50, null=True)),
                ('wadmkc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kecamatan')),
                ('wadmkk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kab/Kota')),
                ('wadmpr', models.CharField(blank=True, max_length=100, null=True, verbose_name='Propinsi')),
                ('tipadm', models.IntegerField(blank=True, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True, verbose_name='Shape Length 1')),
                ('shape_area_1', models.FloatField(blank=True, null=True, verbose_name='Shape Area 1')),
                ('id_2', models.IntegerField(blank=True, null=True)),
                ('fid', models.IntegerField(blank=True, null=True)),
                ('shape_length', models.FloatField(blank=True, null=True, verbose_name='Shape Length 2')),
                ('shape_area_2', models.FloatField(blank=True, null=True, verbose_name='Shape Area 2')),
                ('gridcode', models.IntegerField(blank=True, null=True)),
                ('month', models.CharField(blank=True, max_length=20, null=True)),
                ('dem_min', models.FloatField(blank=True, null=True)),
                ('dem_max', models.FloatField(blank=True, null=True)),
                ('dem_mean', models.FloatField(blank=True, null=True)),
                ('dem_std', models.FloatField(blank=True, null=True)),
                ('avg_slope', models.FloatField(blank=True, null=True)),
                ('potensi_banjir', models.BooleanField(default=False)),
                ('dist_to_river', models.FloatField(blank=True, null=True)),
                ('flood_elev', models.FloatField(blank=True, null=True)),
                ('river_elev', models.FloatField(blank=True, null=True)),
                ('risk_score', models.IntegerField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=50, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='FloodRiskPoint',
        ),
    ]
