# Generated by Django 5.0.3 on 2025-04-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data_services', '0020_floodpoint_delete_floodriskpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='floodpoint',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
