# Generated by Django 5.0.3 on 2025-04-20 08:54

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data_services', '0021_floodpoint_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floodpoint',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
